### ISSUE TITLE
"Error accessing Zulip secrets; manage.py in production must be run  as the zulip user." from new installation

### ISSUE THREAD

**Issue by emacsen** [zulip/docker-zulip#517]
When running the recommended commands to get an organizational token, no response happens on the command line:

```
root@myhost:/srv/docker/docker-zulip# docker-compose exec -u zulip zulip \
    "/home/zulip/deployments/current/manage.py generate_realm_creation_link"
```

Tunning the command manually from the container, I see:

```
zulip@d41bf37f08be:~/deployments/current$ ./manage.py generate_realm_creation_link
Error accessing Zulip secrets; manage.py in production must be run as the zulip user.
```

This is despite me being the `zulip` user.

Digging into 'manage.py', I see:

```
    PRODUCTION = config_file.has_option("machine", "deploy_type")
    HAS_SECRETS = os.access("/etc/zulip/zulip-secrets.conf", os.R_OK)

    if PRODUCTION and not HAS_SECRETS:
        # The best way to detect running manage.py as another user in
        # production before importing anything that would require that
        # access is to check for access to /etc/zulip/zulip.conf (in
        # which case it's a production server, not a dev environment)
        # and lack of access for /etc/zulip/zulip-secrets.conf (which
        # should be only readable by root and zulip)
        print(
            "Error accessing Zulip secrets; manage.py in production must be run 
as the zulip user."
        )
        sys.exit(1)
```

But the location of `zulip-secrets.conf` is not `/etc/zulip`, it's `/data` and thus this can never be satisfied:

```
zulip@20c1930378f1:~/deployments/current$ ls -lad /data/zulip-secrets.conf 
-rw-r----- 1 zulip zulip 728 Oct 18 18:25 /data/zulip-secrets.conf
```

There is a `zulip.conf` file:

```
zulip@20c1930378f1:~/deployments/current$ ls -lad /etc/zulip/zulip.conf 
-rw-r--r-- 1 zulip zulip 102 Sep 16 14:15 /etc/zulip/zulip.conf
```

I don't know the intent on which file is meant to be accessed here, but in either case, it's wrong and thus `manage.py` won't work.

**Comment by timabbott** [comment]
This was fixed in 63819f50b68a8024dffc7151a10fd9b1ac41b894.

**Comment by wandhydrant** [comment]
I got this exact error while upgrading from docker-zulip 11.5 to the new 12.0. The 11.5 version still used bind mounts, I first converted those into volumes. The new zulip container would run manage.py through the entrypoint.sh code and produce this error. As @emacsen wrote, the volume with zulip-secrets.conf was mounted under /data but manage.py would want to find it in /etc/zulip.

After reading this bug and the entrypoint script, I set ``LINK_SETTINGS_TO_DATA: True`` as an environment variable for the zulip container in the override file, and it all worked. I'm not sure how it can work for people without that variable?

**Comment by alexmv** [comment]
Can you share what your config looked like on 11.5?

**Comment by wandhydrant** [comment]
Apologies, my former config was not what I thought it was. It had both ``LINK_SETTINGS_TO_DATA`` and ``MANUAL_CONFIGURATION`` (because of OIDC config with get_secret() ) so it was my mistake not to keep them.

**Comment by funkyfuture** [comment]
i'm also still facing this error message with the recent version 12 releases (`ghcr.io/zulip/zulip-server:12.1-0`. 

i could track the error down to the fact that with the upgrade from a 10.3 release, the symbolic link `/etc/zulip/zulip-secrets.conf` to `/data/zulip-secrets.conf` vanished.

what's also irritating is the fact the the referenced contents of 083aafd2c2aeed3e6bf938c4fb5736fe43bad985 do not appear in the container's `/usr/sbin/entrypoint.sh`.

any hints how this could be fixed in a way that will last over future upgrades?

i could also elaborate why the error message is rather confusing, particularly given the check that leads to it.
